steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - frontend-pr-test:$SHORT_SHA
      - -f
      - app/upstream/microservices-demo/src/frontend/Dockerfile
      - app/upstream/microservices-demo/src/frontend

options:
  logging: CLOUD_LOGGING_ONLY